
parameters:
  _param:
    kubernetes_admin_user: admin
    kubernetes_admin_password: nLShrTSz5U4eKrjH
    kubernetes_admin_token: Zsvf5paBkTMkIwIKQWFBr4vKJ2RTosY6
    kubernetes_kubelet_token: vn2vJ34HBAxgZ7S7sHKYZFlKkLbNhi6y
    kubernetes_kube-proxy_token: h4zrmoxYJEv3Dyf3SJ4weUIptKM5Q8V6
    kubernetes_scheduler_token: 97a02ER9fgtoqoOJgjQBlUo2OxCjpeOd
    kubernetes_controller-manager_token: eBK3p102xkjIBroJJlHQmXOalqd4zGZK
    kubernetes_dns_token: OOkpqo55FZrh7WHUCH8eoJNwBDELmJ8e
    etcd_initial_token: 5b25gQvVekrqQnadQNpkmrO3o6fV42iI
    kubernetes_internal_api_address: 10.254.0.1
    kubernetes_internal_dns_address: 10.254.0.1
    cluster_vip_address: ${_param:kubernetes_control_address}
    cluster_local_address: ${_param:single_address}
    cluster_node01_hostname: ${_param:kubernetes_control_node01_hostname}
    cluster_node01_address: ${_param:kubernetes_control_node01_address}
    cluster_node01_port: 4001
    cluster_node02_hostname: ${_param:kubernetes_control_node02_hostname}
    cluster_node02_address: ${_param:kubernetes_control_node02_address}
    cluster_node02_port: 4001
    cluster_node03_hostname: ${_param:kubernetes_control_node03_hostname}
    cluster_node03_address: ${_param:kubernetes_control_node03_address}
    cluster_node03_port: 4001
    calico_private_network: 192.168.0.0
    calico_private_netmask: 16
  linux:
    network:
      host:
        ctl:
          address: ${_param:kubernetes_control_address}
          names:
          - ${_param:kubernetes_control_hostname}
          - ${_param:kubernetes_control_hostname}.${_param:cluster_domain}
        ctl01:
          address: ${_param:kubernetes_control_node01_address}
          names:
          - ${_param:kubernetes_control_node01_hostname}
          - ${_param:kubernetes_control_node01_hostname}.${_param:cluster_domain}
        ctl02:
          address: ${_param:kubernetes_control_node02_address}
          names:
          - ${_param:kubernetes_control_node02_hostname}
          - ${_param:kubernetes_control_node02_hostname}.${_param:cluster_domain}
        ctl03:
          address: ${_param:kubernetes_control_node03_address}
          names:
          - ${_param:kubernetes_control_node03_hostname}
          - ${_param:kubernetes_control_node03_hostname}.${_param:cluster_domain}
        cmp01:
          address: ${_param:kubernetes_compute_node01_single_address}
          names:
          - ${_param:kubernetes_compute_node01_hostname}
          - ${_param:kubernetes_compute_node01_hostname}.${_param:cluster_domain}
        cmp02:
          address: ${_param:kubernetes_compute_node02_single_address}
          names:
          - ${_param:kubernetes_compute_node02_hostname}
          - ${_param:kubernetes_compute_node02_hostname}.${_param:cluster_domain}
      resolv:
        dns:
          - ${_param:kubernetes_internal_dns_address}
          - ${_param:external_dns_address}
        domain: ${_param:cluster_domain}
        options:
          - ndots:5
          - timeout:2
          - attempts:2

